version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - db
      - prisma
    networks:
      - app-network

  db:
    image: postgres
    container_name: warmy-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  prisma:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: npx prisma migrate dev
    environment:
      - .env
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
